[package]
name = "tui-radar-sim"
version = "0.1.0"
edition = "2024"


[lib]
path = "src/lib.rs"
name = "tui_radar_sim_core"


[[bin]]
path = "src/main.rs"
name = "tui_radar_sim"


[dependencies]
ratatui = "0.29.0"
rand = "0.9.2"